obj-$(CONFIG_DMABUF_HEAPS_SYSTEM)	+= system_heap.o
obj-$(CONFIG_DMABUF_HEAPS_CMA)	+= cma_heap.o
obj-$(CONFIG_DMABUF_HEAPS_CARVEOUT)	+= carveout_heap.o
# shared helpers, built once when the framework is enabled
obj-$(CONFIG_DMABUF_HEAPS)	+= heap-helpers.o
